variable "namespace" {}
variable "cluster_name" {}
variable "image_tag" {}
variable "app_name" {}
variable "docker_registry" {}
variable "domain" {}
variable "tls-cert" {}
variable "tls-key" {}
variable "enabled" {}
variable "external_cert" {}
